use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'Hdk_Example' do
  pod 'Hdk', :path => '../'
  #  pod 'Hdk', '1.0.6'
  pod 'SDWebImage'
  pod 'Masonry'
  
  target 'Hdk_Tests' do
    inherit! :search_paths

  end
  
end
